Revert "direnv: Use simpler/faster/non-persistent use_nix"
This reverts commit 0f0ea9f34e0a0719db1ee8c543dfc951690322ef.

diff --git a/dotfiles/direnv/direnvrc b/dotfiles/direnv/direnvrc
--- a/dotfiles/direnv/direnvrc
+++ b/dotfiles/direnv/direnvrc
@@ -1,36 +1,80 @@
 #!/usr/bin/env bash
 
+# Usage: use_nix [...]
+#
+# Load environment variables from `nix-shell`.
+# If you have a `default.nix` or `shell.nix` one of these will be used and
+# the derived environment will be stored at ./.direnv/<hash>-<filename>.nix
+# and symlink to it will be created at ./.direnv/default.
+# Dependencies are added to the GC roots, such that the environment remains persistent.
+#
+# Packages can also be specified directly via e.g `use nix -p ocaml`,
+# however those will not be added to the GC roots.
+#
+# The resulting environment is cached for better performance.
+#
+# To trigger switch to a different environment:
+# `rm -f .direnv/default`
+#
+# To derive a new environment:
+# `rm -rf .direnv/env-$(md5sum {shell,default}.nix 2> /dev/null | cut -c -32)`
+#
+# To remove cache:
+# `rm -f .direnv/dump-*`
+#
+# To remove all environments:
+# `rm -rf .direnv/env-*`
+#
+# To remove only old environments: 
+# `find .direnv -name 'env-*' -and -not -name `readlink .direnv/default` -exec rm -rf {} +`
+#
 use_nix() {
-  local path="$(nix-instantiate --find-file nixpkgs)"
+    set -e
 
-  if [ -f "${path}/.version-suffix" ]; then
-    local version="$(< $path/.version-suffix)"
-  elif [ -f "${path}/.git" ]; then
-    local version="$(< $(< ${path}/.git/HEAD))"
-  fi
+    local shell="shell.nix"
+    if [[ ! -f "${shell}" ]]; then
+        shell="default.nix"
+    fi
 
-  local cache=".direnv/cache-${version:-unknown}"
+    if [[ ! -f "${shell}" ]]; then
+        fail "use nix: shell.nix or default.nix not found in the folder"
+    fi
 
-  if [[ ! -e "$cache" ]] || \
-    [[ "$HOME/.direnvrc" -nt "$cache" ]] || \
-    [[ .envrc -nt "$cache" ]] || \
-    [[ default.nix -nt "$cache" ]] || \
-    [[ shell.nix -nt "$cache" ]];
-  then
-    [ -d .direnv ] || mkdir .direnv
-    local tmp=$(nix-shell --show-trace --pure "$@" \
-      --run "\"$direnv\" dump bash")
-    echo "$tmp" > "$cache"
-  fi
+    local dir="${PWD}"/.direnv
+    local default="${dir}/default"
+    if [[ ! -L "${default}" ]] || [[ ! -d `readlink "${default}"` ]]; then
+        local wd="${dir}/env-`md5sum "${shell}" | cut -c -32`" # TODO: Hash also the nixpkgs version?
+        mkdir -p "${wd}"
 
-  local path_backup=$PATH
-  eval "$(< $cache)"
-  export PATH=$PATH:$path_backup
+        local drv="${wd}/env.drv"
+        if [[ ! -f "${drv}" ]]; then
+            log_status "use nix: deriving new environment"
+            IN_NIX_SHELL=1 nix-instantiate --add-root "${drv}" --indirect "${shell}" > /dev/null
+            nix-store -r `nix-store --query --references "${drv}"` --add-root "${wd}/dep" --indirect > /dev/null
+        fi
 
-  if [[ $# = 0 ]]; then
-    watch_file default.nix
+        rm -f "${default}"
+        ln -s `basename "${wd}"` "${default}"
+    fi
+
+    local drv=`readlink -f "${default}/env.drv"`
+    local dump="${dir}/dump-`md5sum ".envrc" | cut -c -32`-`md5sum ${drv} | cut -c -32`"
+
+    if [[ ! -f "${dump}" ]] || [[ "${XDG_CONFIG_DIR}/direnv/direnvrc" -nt "${dump}" ]]; then
+        log_status "use nix: updating cache"
+
+        old=`find ${dir} -name 'dump-*'`
+        nix-shell "${drv}" --show-trace "$@" --run 'direnv dump' > "${dump}"
+        rm -f ${old}
+    fi
+
+    direnv_load cat "${dump}"
+
+    watch_file "${default}"
     watch_file shell.nix
-  fi
+    if [[ ${shell} == "default.nix" ]]; then
+        watch_file default.nix
+    fi
 }
 
 # vim: set ft=bash
